### ISSUE TITLE
Installation of docker-compose may fail when local system is a different architecture

### ISSUE THREAD

**Issue by dhauenstein** [khast3x/Redcloud#17]
During installation on a remote host via ssh, docker-compose gets installed.
To determine the correct platform to download and install docker-compose, uname is called, but on the local system. If the architecture is different to the remote host's architecture, an incorrect binary version of docker-compose is installed.

Should be fixed with PR #16

**Comment by khast3x** [comment]
Hey @dhauenstein, thank you for finding and fixing this bug.   
Much appreciated! Cheers

:arrow_right: PR merged
