### ISSUE TITLE
Local deployment fails on macOS

### ISSUE THREAD

**Issue by Ullaakut** [khast3x/Redcloud#3]
👋🏽@khast3x !

Decided to give Redcloud a try since it looks pretty awesome, but I haven't been able to deploy it locally on my macOS machine.

![Screenshot 2019-03-17 at 16 29 39](https://user-images.githubusercontent.com/6976628/54493630-741e8500-48d2-11e9-9346-e8743354c669.png)

Here is some info that might help in understanding what's going on:

- **OS**: macOS `10.14.3 (18D109)` (darwin amd64)
- **`docker-compose` version**: `1.23.2, build 1110ad01`
- **`docker-py` version**: `3.6.0`
- **Docker client version**: `18.09.2` (Docker Desktop)
- **Docker engine version**: `18.09.2` (Docker Engine - Community)

When running `docker-compose up --build -d` manually to get the logs, I'm getting:

```go
Starting portainer-app       ... error
Starting redcloud_cert_gen_1 ...

ERROR: for portainer-app  Cannot start service portainer: b'Mounts denied: \r\nThe path /opt/portainer/data\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more iStarting redcloud_cert_gen_1 ... done
portainer-proxy is up-to-date

ERROR: for portainer  Cannot start service portainer: b'Mounts denied: \r\nThe path /opt/portainer/data\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'
ERROR: Encountered errors while bringing up the project.
```

Which seems to be related to the fact that the volume `/opt/portainer/data` that is specified in the compose file is not shared by default on macOS. Unfortunately, it seems that the current version of Docker for Mac doesn't even allow users to mount anything in `/opt` 😞

## Conclusion

In order to support macOS deployment, it seems all that is needed is to allow users to customize the path in which portainer data is stored 🤔

Let me know if that makes sense to you!

**Comment by Ullaakut** [comment]
(For info, after changing the volume location to `./data`, works like a charm)

**Comment by khast3x** [comment]
Hey there, thanks for giving redcloud a try!  
Glad to know changing the volume source solved the mounting issue. Started [reading a bit more about it[(https://apple.stackexchange.com/questions/119230/what-is-standard-for-os-x-filesystem-e-g-opt-vs-usr). Not quite sure how to tackle this issue in a viable way :thinking:     
I'll update the documentation so as to replace with `/tmp/` for OSX deploys in troubleshooting for now

**Comment by khast3x** [comment]
Closing with commit https://github.com/khast3x/Redcloud/commit/266c5a79721196c0d26710043d625ed6a189e77d
